name: build firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Prepare build environment
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    
    - name: Fetch code
      uses: actions/checkout@v6
      with:
        submodules: recursive
    
    - name: Build firmware
      run: |
        cmake --preset MinSizeRel
        cmake --build build/MinSizeRel
    
    - name: Upload firmware
      uses: actions/upload-artifact@v7
      with:
        name: ${{ github.event.repository.name }}-${{ github.run_id }}
        path: |
          build/MinSizeRel/U2HTS_F070F6.hex
          build/MinSizeRel/U2HTS_F070F6.bin
